version: '3.8'

services:

  backend:
    build: ./project_atlas
    ports:
      - 5000:5000
    volumes:
      - ./project_atlas:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
