CREATE TABLE IF NOT EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exercises (
    ID INTEGER PRIMARY KEY AUTOINCREMENT ,
    NAME TEXT NOT NULL UNIQUE ,
    DESCRIPTION TEXT,
    TARGET_MUSCLE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workouts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT ,
    USER_ID INTEGER NOT NULL ,
    EXERCISE_ID INTEGER NOT NULL ,
    SETS INTEGER NOT NULL ,
    REPETITIONS INTEGER NOT NULL ,
    WEIGHT FLOAT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES users(ID),
    FOREIGN KEY(EXERCISE_ID) REFERENCES exercises(ID)
);