// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Exercise struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	TargetMuscle string `json:"target_muscle"`
	Creator      *User  `json:"Creator"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewExercise struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	TargetMuscle string `json:"target_muscle"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
